version: "3.8"

volumes:
  db-data:

services:
  database:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - "db-data:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    container_name: django
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
    # ports:
    #   - "8000:8000"  # バックエンドのポート設定
    expose:
        - "8000"
    tty: true
    command: >
      /bin/sh -c '
      cd ./django_app/ &&
      poetry run gunicorn -w 4 django_app.wsgi:application --bind 0.0.0.0:8000
      '
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend  

  # frontend:
  #   container_name: react
  #   build:
  #     context: .
  #     dockerfile: ./front/React/Dockerfile
  #   volumes:
  #     - ./front/React:/React
  #     - /React/node_modules
  #   ports:
  #     - "5173:5173"  # フロントエンドのポート設定
  #   tty: true
  #   command: /bin/sh -c "npm run dev"